version: '3.9'

services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  app:
    build: .
    tty: true
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env

volumes:
  pg_data:
